In [9]:
import tensorflow as tf

In [10]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142]


In [11]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [12]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [13]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [14]:
sess = tf.Session()

In [15]:
sess.run(tf.global_variables_initializer())

In [16]:
num = 2001
for step in range(num):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 10 == 0 or step == num-1:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  26657.219 
Prediction
 [ 9.643702  8.774477 10.413683  7.257082  9.403116]
10 Cost:  3.9079483 
Prediction
 [154.0607  182.36176 181.44756 193.50992 141.80765]
20 Cost:  3.655925 
Prediction
 [154.49295 182.89015 181.96352 194.07306 142.21182]
30 Cost:  3.6479847 
Prediction
 [154.48958 182.89491 181.96358 194.07439 142.21658]
40 Cost:  3.6400948 
Prediction
 [154.4849  182.89806 181.96205 194.07399 142.22011]
50 Cost:  3.6321921 
Prediction
 [154.48018 182.90117 181.96051 194.07361 142.2236 ]
60 Cost:  3.6243749 
Prediction
 [154.47554 182.90431 181.95897 194.07321 142.22714]
70 Cost:  3.6165662 
Prediction
 [154.47087 182.90744 181.95746 194.07283 142.23064]
80 Cost:  3.608787 
Prediction
 [154.4662  182.91055 181.95593 194.07243 142.23412]
90 Cost:  3.6010997 
Prediction
 [154.4616  182.91367 181.95444 194.07205 142.23761]
100 Cost:  3.5934143 
Prediction
 [154.45697 182.91676 181.95293 194.07167 142.24107]
110 Cost:  3.585773 
Prediction
 [154.45236 182.91985 181.95143 194

1060 Cost:  2.9993067 
Prediction
 [154.06325 183.17987 181.82358 194.04535 142.5297 ]
1070 Cost:  2.994367 
Prediction
 [154.05962 183.1823  181.82239 194.04517 142.53226]
1080 Cost:  2.9894297 
Prediction
 [154.056   183.18471 181.82118 194.04501 142.53484]
1090 Cost:  2.9845643 
Prediction
 [154.0524  183.1871  181.82    194.04485 142.53743]
1100 Cost:  2.9796658 
Prediction
 [154.0488  183.1895  181.8188  194.0447  142.53998]
1110 Cost:  2.9748359 
Prediction
 [154.04521 183.19188 181.81761 194.04451 142.54253]
1120 Cost:  2.9700248 
Prediction
 [154.04163 183.19426 181.81644 194.04433 142.54506]
1130 Cost:  2.9652247 
Prediction
 [154.03806 183.19662 181.81525 194.04416 142.54759]
1140 Cost:  2.9604292 
Prediction
 [154.03452 183.19902 181.81406 194.044   142.55014]
1150 Cost:  2.9556649 
Prediction
 [154.03093 183.20135 181.81287 194.04382 142.55264]
1160 Cost:  2.9509087 
Prediction
 [154.0274  183.20375 181.81172 194.0437  142.55518]
1170 Cost:  2.9461992 
Prediction
 [154.0238

In [18]:
print("hello World")

hello World
