In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142]


In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()

In [8]:
sess.run(tf.global_variables_initializer())

In [13]:
num = 2001
for step in range(num):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 10 == 0 or step == num-1:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  1.4244639 
Prediction
 [150.57103 185.06206 180.03532 197.88965 140.77342]
10 Cost:  1.4238379 
Prediction
 [150.57121 185.062   180.03545 197.8892  140.7738 ]
20 Cost:  1.4232152 
Prediction
 [150.5714  185.06192 180.03557 197.88875 140.77415]
30 Cost:  1.4225895 
Prediction
 [150.57158 185.06186 180.03569 197.8883  140.77454]
40 Cost:  1.4219756 
Prediction
 [150.57175 185.06178 180.03581 197.88785 140.77489]
50 Cost:  1.4213574 
Prediction
 [150.57193 185.0617  180.03593 197.8874  140.77525]
60 Cost:  1.4207323 
Prediction
 [150.57211 185.06165 180.03607 197.88696 140.77563]
70 Cost:  1.420112 
Prediction
 [150.57228 185.06158 180.0362  197.8865  140.776  ]
80 Cost:  1.4195015 
Prediction
 [150.57246 185.06151 180.03632 197.88606 140.77635]
90 Cost:  1.4188726 
Prediction
 [150.57265 185.06145 180.03642 197.8856  140.77672]
100 Cost:  1.418267 
Prediction
 [150.57283 185.06139 180.03656 197.88518 140.77708]
110 Cost:  1.4176389 
Prediction
 [150.57301 185.06133 180.0367  19

1040 Cost:  1.3615888 
Prediction
 [150.59009 185.05463 180.04828 197.84377 140.81033]
1050 Cost:  1.3610085 
Prediction
 [150.59026 185.05455 180.04839 197.84332 140.81067]
1060 Cost:  1.3604124 
Prediction
 [150.59044 185.05446 180.04851 197.84288 140.81102]
1070 Cost:  1.3598275 
Prediction
 [150.59064 185.0544  180.04865 197.84245 140.81136]
1080 Cost:  1.3592393 
Prediction
 [150.59082 185.05432 180.04877 197.84201 140.81169]
1090 Cost:  1.358655 
Prediction
 [150.591   185.05423 180.04889 197.84158 140.81204]
1100 Cost:  1.35807 
Prediction
 [150.5912  185.05417 180.04901 197.84116 140.81238]
1110 Cost:  1.3574779 
Prediction
 [150.5914  185.0541  180.04915 197.84073 140.81273]
1120 Cost:  1.3568984 
Prediction
 [150.59157 185.054   180.04926 197.84029 140.81306]
1130 Cost:  1.3563113 
Prediction
 [150.59175 185.05392 180.0494  197.83984 140.8134 ]
1140 Cost:  1.3557107 
Prediction
 [150.59196 185.05385 180.04951 197.83942 140.81375]
1150 Cost:  1.3551319 
Prediction
 [150.59213 