In [12]:
import tensorflow as tf
import numpy as np

In [13]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [14]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]

In [15]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [16]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [17]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [18]:
hypothesis = tf.matmul(X,W) + b

In [19]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [20]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [21]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [56]:
result = []
template = "{} Cost : {} \nPrediction:\n {}"
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict = {X: x_data, Y: y_data})
    if step % 10 == 0:
        str = template.format(step, cost_val, hy_val)
        result.append(str)

import pandas as pd
result = pd.DataFrame(result)

for i in result.values:
    print(i)

['0 Cost : 5.9713263511657715 \nPrediction:\n [[152.87814 ]\n [184.69235 ]\n [181.46057 ]\n [199.03177 ]\n [139.7467  ]\n [104.945656]\n [150.52724 ]\n [113.80915 ]\n [174.3565  ]\n [164.44308 ]\n [143.85706 ]\n [142.68503 ]\n [186.15097 ]\n [152.74573 ]\n [151.48575 ]\n [188.62973 ]\n [144.05176 ]\n [181.4828  ]\n [177.09732 ]\n [158.52705 ]\n [176.30377 ]\n [174.46326 ]\n [167.60635 ]\n [151.0051  ]\n [190.69405 ]]']
['10 Cost : 5.971325874328613 \nPrediction:\n [[152.87816]\n [184.69234]\n [181.46057]\n [199.03178]\n [139.74672]\n [104.94564]\n [150.52724]\n [113.80915]\n [174.35649]\n [164.4431 ]\n [143.85704]\n [142.68503]\n [186.15096]\n [152.74573]\n [151.48576]\n [188.62971]\n [144.05174]\n [181.4828 ]\n [177.0973 ]\n [158.52705]\n [176.30376]\n [174.46324]\n [167.60637]\n [151.00511]\n [190.69405]]']
['20 Cost : 5.971309185028076 \nPrediction:\n [[152.87814]\n [184.69235]\n [181.46057]\n [199.03177]\n [139.7467 ]\n [104.94563]\n [150.52725]\n [113.80916]\n [174.35649]\n [164.4

In [24]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[100, 70,101]]}))

Your score wil be [[190.97168]]


In [25]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[60, 70,110], [90, 100, 80]]}))

Your score wil be [[175.18008]
 [175.61021]]


In [26]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[200, 270,201]]}))

Your score wil be [[433.72437]]


In [27]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[-200, -270,-201]]}))

Your score wil be [[-435.3637]]


In [28]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[2200, 2270,9201]]}))

Your score wil be [[11536.291]]
