In [1]:
import tensorflow as tf

In [19]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [143.],
          [142.]]

In [26]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
hypothesis

<tf.Tensor 'add_3:0' shape=(?, 1) dtype=float32>

In [25]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
cost

<tf.Tensor 'Mean_3:0' shape=() dtype=float32>

In [27]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
train

<tf.Operation 'GradientDescent_4' type=NoOp>

In [23]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

In [24]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  4293.0493 
Prediction:
 [[ 81.66966 ]
 [118.560234]
 [105.95452 ]
 [119.27775 ]
 [ 92.359406]
 [ 92.359406]]
10 Cost:  32.525803 
Prediction:
 [[141.02525]
 [189.8796 ]
 [176.23808]
 [195.81198]
 [146.75511]
 [146.75511]]
20 Cost:  32.26314 
Prediction:
 [[141.32658]
 [190.20055]
 [176.57579]
 [196.17696]
 [146.99193]
 [146.99193]]
30 Cost:  32.094204 
Prediction:
 [[141.35222]
 [190.1901 ]
 [176.58698]
 [196.18639]
 [146.97601]
 [146.97601]]
40 Cost:  31.926376 
Prediction:
 [[141.37648]
 [190.17818]
 [176.59665]
 [196.19414]
 [146.95898]
 [146.95898]]
50 Cost:  31.759453 
Prediction:
 [[141.40068]
 [190.16626]
 [176.60623]
 [196.20184]
 [146.94199]
 [146.94199]]
60 Cost:  31.593485 
Prediction:
 [[141.42479]
 [190.15436]
 [176.61581]
 [196.20949]
 [146.92503]
 [146.92503]]
70 Cost:  31.428476 
Prediction:
 [[141.44882]
 [190.1425 ]
 [176.62537]
 [196.21713]
 [146.90811]
 [146.90811]]
80 Cost:  31.264414 
Prediction:
 [[141.47284]
 [190.1307 ]
 [176.63489]
 [196.2248 ]
 [146.

820 Cost:  21.426565 
Prediction:
 [[143.06908]
 [189.34364]
 [177.26913]
 [196.72647]
 [145.77455]
 [145.77455]]
830 Cost:  21.32043 
Prediction:
 [[143.08841]
 [189.3341 ]
 [177.27682]
 [196.73248]
 [145.7611 ]
 [145.7611 ]]
840 Cost:  21.214937 
Prediction:
 [[143.10768]
 [189.3246 ]
 [177.2845 ]
 [196.73846]
 [145.74768]
 [145.74768]]
850 Cost:  21.110003 
Prediction:
 [[143.1269 ]
 [189.31511]
 [177.29213]
 [196.7444 ]
 [145.7343 ]
 [145.7343 ]]
860 Cost:  21.005774 
Prediction:
 [[143.14604]
 [189.30565]
 [177.29973]
 [196.75032]
 [145.72095]
 [145.72095]]
870 Cost:  20.902063 
Prediction:
 [[143.16516]
 [189.29622]
 [177.30733]
 [196.75624]
 [145.70766]
 [145.70766]]
880 Cost:  20.79891 
Prediction:
 [[143.18422]
 [189.2868 ]
 [177.3149 ]
 [196.76213]
 [145.69438]
 [145.69438]]
890 Cost:  20.696394 
Prediction:
 [[143.20323]
 [189.27742]
 [177.32246]
 [196.76802]
 [145.68118]
 [145.68118]]
900 Cost:  20.594433 
Prediction:
 [[143.22218]
 [189.26808]
 [177.33   ]
 [196.77386]
 [1

1600 Cost:  14.743308 
Prediction:
 [[144.4223 ]
 [188.6751 ]
 [177.80717]
 [197.13933]
 [144.83725]
 [144.83725]]
1610 Cost:  14.675644 
Prediction:
 [[144.43776]
 [188.66743]
 [177.81332]
 [197.14395]
 [144.8266 ]
 [144.8266 ]]
1620 Cost:  14.608365 
Prediction:
 [[144.45319]
 [188.65982]
 [177.81946]
 [197.14857]
 [144.81598]
 [144.81598]]
1630 Cost:  14.541447 
Prediction:
 [[144.46858]
 [188.6522 ]
 [177.82559]
 [197.15318]
 [144.80542]
 [144.80542]]
1640 Cost:  14.474972 
Prediction:
 [[144.48387]
 [188.64459]
 [177.83168]
 [197.15773]
 [144.79485]
 [144.79485]]
1650 Cost:  14.408859 
Prediction:
 [[144.49918]
 [188.63704]
 [177.83777]
 [197.16232]
 [144.78435]
 [144.78435]]
1660 Cost:  14.343125 
Prediction:
 [[144.51443]
 [188.62953]
 [177.84384]
 [197.16689]
 [144.77386]
 [144.77386]]
1670 Cost:  14.277736 
Prediction:
 [[144.52963]
 [188.622  ]
 [177.84987]
 [197.1714 ]
 [144.7634 ]
 [144.7634 ]]
1680 Cost:  14.212758 
Prediction:
 [[144.54478]
 [188.61449]
 [177.8559 ]
 [197