In [1]:
import tensorflow as tf
import numpy as np

/Users/labry/anaconda3/envs/tf-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/labry/anaconda3/envs/tf-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/labry/anaconda3/envs/tf-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/labry/anaconda3/envs/tf-env/lib/python3

In [2]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [3]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]

In [4]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [5]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [6]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
hypothesis = tf.matmul(X,W) + b

In [8]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [9]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [11]:
result = []
template = "{} Cost : {} \nPrediction:\n {}"
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict = {X: x_data, Y: y_data})
    if step % 10 == 0:
        str = template.format(step, cost_val, hy_val)
        result.append(str)

import pandas as pd
result = pd.DataFrame(result)

for i in result.values:
    print(i)

['0 Cost : 27428.57421875 \nPrediction:\n [[-16.860994  ]\n [  6.316388  ]\n [ -7.8583555 ]\n [ -2.7352324 ]\n [  6.4112597 ]\n [ 16.404211  ]\n [ -1.1671019 ]\n [ -0.32419866]\n [ 18.967985  ]\n [ 32.535137  ]\n [  0.81528956]\n [ 14.63223   ]\n [-13.486712  ]\n [-17.792727  ]\n [  3.4079409 ]\n [  9.450513  ]\n [-15.7644    ]\n [ -3.7006407 ]\n [-17.878008  ]\n [-17.914324  ]\n [  0.5463076 ]\n [  9.772     ]\n [ -3.3953276 ]\n [-29.702913  ]\n [ -0.25723547]]']
['10 Cost : 154.27503967285156 \nPrediction:\n [[137.40546 ]\n [191.63104 ]\n [174.78821 ]\n [196.15892 ]\n [147.73718 ]\n [120.552795]\n [147.70761 ]\n [110.039085]\n [192.10806 ]\n [192.84787 ]\n [144.24115 ]\n [156.00092 ]\n [175.233   ]\n [139.11304 ]\n [152.9497  ]\n [197.48972 ]\n [133.66336 ]\n [174.97284 ]\n [162.05801 ]\n [143.09232 ]\n [175.11905 ]\n [183.60712 ]\n [163.06064 ]\n [125.882866]\n [191.82584 ]]']
['20 Cost : 151.72573852539062 \nPrediction:\n [[138.52893]\n [192.8821 ]\n [176.0738 ]\n [197.5375 ]\n [14

In [12]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[100, 70,101]]}))

Your score wil be [[215.7118]]


In [13]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[60, 70,110], [90, 100, 80]]}))

Your score wil be [[196.66267]
 [159.81767]]


In [14]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[200, 270,201]]}))

Your score wil be [[372.63864]]


In [15]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[-200, -270,-201]]}))

Your score wil be [[-374.56625]]


In [16]:
print("Your score wil be", sess.run(hypothesis, 
                                   feed_dict={X:[[2200, 2270,9201]]}))

Your score wil be [[15761.3955]]
