In [1]:
import tensorflow as tf

/Users/labry/anaconda3/envs/tf-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/labry/anaconda3/envs/tf-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/labry/anaconda3/envs/tf-env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/labry/anaconda3/envs/tf-env/lib/python3

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142]


In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()

In [7]:
sess.run(tf.global_variables_initializer())

In [8]:
num = 2001
for step in range(num):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    
    if step % 10 == 0 or step == num-1:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)

0 Cost:  7875.014 
Prediction
 [85.0476   82.45848  91.928024 94.42108  62.610237]
10 Cost:  55.70437 
Prediction
 [163.24178 176.49596 184.55667 195.29538 134.34717]
20 Cost:  55.347942 
Prediction
 [163.44995 176.79993 184.8281  195.59505 134.58902]
30 Cost:  55.064583 
Prediction
 [163.42216 176.82018 184.82011 195.59041 134.61446]
40 Cost:  54.78294 
Prediction
 [163.3938  176.83955 184.81133 195.58485 134.63916]
50 Cost:  54.502728 
Prediction
 [163.36552 176.85886 184.80252 195.57935 134.66385]
60 Cost:  54.224133 
Prediction
 [163.33731 176.87813 184.79381 195.57385 134.68843]
70 Cost:  53.946888 
Prediction
 [163.30916 176.89737 184.7851  195.56836 134.71294]
80 Cost:  53.67113 
Prediction
 [163.28108 176.91652 184.77637 195.56287 134.7374 ]
90 Cost:  53.39692 
Prediction
 [163.25308 176.93561 184.76768 195.55742 134.7618 ]
100 Cost:  53.124138 
Prediction
 [163.22516 176.95468 184.759   195.55197 134.78609]
110 Cost:  52.852783 
Prediction
 [163.19728 176.97368 184.75035 195.5

In [9]:
print("hello World")

hello World
